# Cloudflare Pages Configuration
name = "blog-website"
compatibility_date = "2024-09-21"
pages_build_output_dir = "frontend/dist"

# Environment variables for build (better to set in Pages dashboard)
[env.production.vars]
NODE_VERSION = "18"

# Redirects
[[redirects]]
  from = "/admin"
  to = "https://your-project-id.sanity.studio"
  status = 302

[[redirects]]
  from = "/admin/*"
  to = "https://your-project-id.sanity.studio/:splat"
  status = 302