[build]
  command = "cd frontend && npm ci && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  # PUBLIC_SANITY_PROJECT_ID = "your-project-id-here"
  # PUBLIC_SANITY_DATASET = "production"
  # PUBLIC_SANITY_API_VERSION = "2024-01-01"
  # Note: Set these in Cloudflare Pages dashboard instead

[[redirects]]
  from = "/admin"
  to = "https://your-project-id.sanity.studio"
  status = 302

[[redirects]]
  from = "/admin/*"
  to = "https://your-project-id.sanity.studio/:splat"
  status = 302